language: r
r: bioc-release
cache:
  packages: true
bioc_check: true
warnings_are_errors: false
r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes
os:
  - linux
r_packages:
  - covr
  - igraph
  - readr
  - dplyr
  - stringr
after_success:
  - Rscript -e 'covr::codecov()'
